# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
reports:
  exclude_contracts:
    - SafeMath
dependencies:
  - alphachainio/chainlink-contracts@1.1.2
  - OpenZeppelin/openzeppelin-contracts@3.0.0
compiler:
  solc:
    remappings:
      - '@chainlink=alphachainio/chainlink-contracts@1.1.2'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.0.0'
# automatically fetch contract sources from Etherscan
autofetch_sources: True
networks:
  default: development
  kovan:
    btc_usd_price_feed: '0x6135b13325bfC4B00278B4abC5e20bbce2D6580e'
  mainnet:
    btc_usd_price_feed: '0xF4030086522a5bEEa4988F8cA5B36dbC97BeE88c'
wallets:
  from_key: PRIVATE_KEY
  # could also do from_mnemonic, and you'd have to change the accounts.add to accounts.from_mnemonic
